import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='h-screen '>
          <NavBar />
          <div className='mt-8 mx-auto p-4 justify-center'>
            {children}

          </div>
        </div>
      </body>
    </html>
  )
}
